easy-rsa: Make sure hostname and domain contain only valid characters
In general valid domain name consists of letters (in upper and lower
cases), numbers, hyphen, dots and underscope. Make sure hostname and
domain passed via environment and simplify regular expression escaping.

While there move DESTS assignment and inherit statements to the top
of vars-sh to conform with rest of installsh users. Apply default
escaped hostname.domain as $fqdn_regex only when later isn't given
via environment.

Signed-off-by: Serhey Popovych <serhe.popovych@gmail.com>

diff --git a/vars-sh b/vars-sh
--- a/vars-sh
+++ b/vars-sh
@@ -1,19 +1,28 @@
 
-# Install vars
-hostname="${hostname:-easy-rsa}"
-domain="${domain:-example.net}"
-fqdn="${hostname}.${domain}"
-fqdn_regex="$(echo "$fqdn" | sed -n -e 's,\([(){}|.?*+]\|()\),\\\\\1,pg')"
-
 # Project data
 DESTS='/easy-rsa'
 
-SUBST_TEMPLATES="$SUBST_TEMPLATES"'
--e "s,@hostname@,$hostname,g"
--e "s,@domain@,$domain,g"
--e "s,@fqdn@,$fqdn,g"
--e "s,@fqdn_regex@,$fqdn_regex,g"
-'
-
 # Inherit subproject(s) variables
 inherit 'installsh/vars-sh'
+
+# Install vars
+hostname="${hostname:-easy-rsa}" &&
+if [ -z "${hostname##*[^a-zA-Z0-9._-]*}" ]; then
+    echo >&2 "$prog_name: invalid characters in hostname"
+    exit 1
+fi
+domain="${domain:-example.net}"
+if [ -z "${domain##*[^a-zA-Z0-9._-]*}" ]; then
+    echo >&2 "$prog_name: invalid characters in domain"
+    exit 1
+fi
+fqdn="${hostname}.${domain}"
+fqdn_regex="${fqdn_regex:-$(echo "$fqdn" | sed -n -e 's,\(\.\),\\\\\1,pg')}"
+
+SUBST_TEMPLATES="$SUBST_TEMPLATES"'
+-e "s|@hostname@|$hostname|g"
+-e "s|@domain@|$domain|g"
+-e "s|@fqdn@|$fqdn|g"
+-e "s|@fqdn_regex@|$fqdn_regex|g"
+'
+
