easy-rsa: pkitool: Use space for indentation instead of tabs
Current code indentation already aligned to use four spaces instead of
eight. However two, four, six and above levels of indentation use tab
in place of eight spaces. Replace each tab with eight space symbols.

Signed-off-by: Serhey Popovych <serhe.popovych@gmail.com>

diff --git a/easy-rsa/pkitool b/easy-rsa/pkitool
--- a/easy-rsa/pkitool
+++ b/easy-rsa/pkitool
@@ -217,108 +217,153 @@ BATCH="-batch"
 # Process options
 while [ $# -gt 0 ]; do
     case "$1" in
-	--initca)    if [ $DO_ROOT -eq 0 ]; then
-			DO_ROOT="1"
-			DO_REQ="${DO_REQ:-0}"
-			DO_CA="${DO_CA:-0}"
-			DO_P12="${DO_P12:-0}"
-			DO_P11="${DO_P11:-0}"
-		     fi ;;
+        --initca)
+            if [ $DO_ROOT -eq 0 ]; then
+                DO_ROOT="1"
+                DO_REQ="${DO_REQ:-0}"
+                DO_CA="${DO_CA:-0}"
+                DO_P12="${DO_P12:-0}"
+                DO_P11="${DO_P11:-0}"
+            fi
+            ;;
 
-		     # Do not stack extensions so that intermediate CA
-		     # does not have server extensions and key usage.
-	--server)    REQ_EXT="-extensions server"
-		     CA_EXT="-extensions server" ;;
-	--client)    REQ_EXT=""
-		     CA_EXT="" ;;
-	--inter)     REQ_EXT=""
-		     CA_EXT="-extensions v3_ca" ;;
+            # Do not stack extensions so that intermediate CA
+            # does not have server extensions and key usage.
+        --server)
+            REQ_EXT="-extensions server"
+            CA_EXT="-extensions server"
+            ;;
+        --client)
+            REQ_EXT=""
+            CA_EXT=""
+            ;;
+        --inter)
+            REQ_EXT=""
+            CA_EXT="-extensions v3_ca"
+            ;;
 
-	--csr)       DO_REQ="1"
-		     DO_CA="0" ;;
-	--sign)      DO_REQ="2"
-		     DO_CA="1" ;;
+        --csr)
+            DO_REQ="1"
+            DO_CA="0"
+            ;;
+        --sign)
+            DO_REQ="2"
+            DO_CA="1"
+            ;;
 
-	--keysize)   KEY_SIZE=$2
-		     shift ;;
+        --keysize)
+            KEY_SIZE=$2
+            shift
+            ;;
 
-	--md)        KEY_MD="$2"
-		     shift ;;
+        --md)
+            KEY_MD="$2"
+            shift
+            ;;
 
-	--batch)     BATCH="-batch" ;;
-	--interact)  BATCH="" ;;
+        --batch)
+            BATCH="-batch"
+            ;;
+        --interact)
+            BATCH=""
+            ;;
 
-	--pass)      if [ -n "$KEY_PASSPHRASE" ]; then
-			# Must be supplied via KEY_PASSPHRASE environment variable
-			# to hide it from process command line lookup tools.
-			PASS_OPT="$KEY_PASSPHRASE"
-		     fi ;;
+        --pass)
+            if [ -n "$KEY_PASSPHRASE" ]; then
+                # Must be supplied via KEY_PASSPHRASE environment variable
+                # to hide it from process command line lookup tools.
+                PASS_OPT="$KEY_PASSPHRASE"
+            fi
+            ;;
 
-	--pkcs12)    DO_REQ="2"
-		     DO_CA="2"
-		     DO_P12="1" ;;
-	--pkcs11)    DO_REQ="2"
-		     DO_CA="2"
-		     DO_P11="1"
-		     PKCS11_MODULE_PATH="$2"
-		     PKCS11_SLOT="$3"
-		     PKCS11_ID="$4"
-		     PKCS11_LABEL="$5"
-		     shift 4 ;;
+        --pkcs12)
+            DO_REQ="2"
+            DO_CA="2"
+            DO_P12="1"
+            ;;
+        --pkcs11)
+            DO_REQ="2"
+            DO_CA="2"
+            DO_P11="1"
+            PKCS11_MODULE_PATH="$2"
+            PKCS11_SLOT="$3"
+            PKCS11_ID="$4"
+            PKCS11_LABEL="$5"
+            shift 4
+            ;;
 
-	# standalone
-	--pkcs11-init)
-		     PKCS11_MODULE_PATH="$2"
-		     PKCS11_SLOT="$3"
-		     PKCS11_LABEL="$4"
-		     if [ -z "$PKCS11_LABEL" ]; then
-			die "Please specify library name, slot and label"
-		     fi
-		     $PKCS11TOOL --module "$PKCS11_MODULE_PATH" --init-token --slot "$PKCS11_SLOT" \
-			--label "$PKCS11_LABEL" &&
-			$PKCS11TOOL --module "$PKCS11_MODULE_PATH" --init-pin --slot "$PKCS11_SLOT"
-		     exit $? ;;
-	--pkcs11-slots)
-		     PKCS11_MODULE_PATH="$2"
-		     if [ -z "$PKCS11_MODULE_PATH" ]; then
-			die "Please specify library name"
-		     fi
-		     $PKCS11TOOL --module "$PKCS11_MODULE_PATH" --list-slots
-		     exit 0 ;;
-	--pkcs11-objects)
-		     PKCS11_MODULE_PATH="$2"
-		     PKCS11_SLOT="$3"
-		     if [ -z "$PKCS11_SLOT" ]; then
-			die "Please specify library name and slot"
-		     fi
-		     $PKCS11TOOL --module "$PKCS11_MODULE_PATH" --list-objects --login --slot "$PKCS11_SLOT"
-		     exit 0 ;;
+        # standalone
+        --pkcs11-init)
+            PKCS11_MODULE_PATH="$2"
+            PKCS11_SLOT="$3"
+            PKCS11_LABEL="$4"
+            [ -n "$PKCS11_LABEL" ] ||
+                die 'Please specify library name, slot and label'
+            $PKCS11TOOL \
+                --module "$PKCS11_MODULE_PATH" \
+                --init-token \
+                --slot "$PKCS11_SLOT" \
+                --label "$PKCS11_LABEL" &&
+            $PKCS11TOOL \
+                --module "$PKCS11_MODULE_PATH" \
+                --init-pin \
+                --slot "$PKCS11_SLOT" \
+                #
+            exit $?
+            ;;
+        --pkcs11-slots)
+            PKCS11_MODULE_PATH="$2"
+            [ -n "$PKCS11_MODULE_PATH" ] ||
+                die 'Please specify library name'
+            $PKCS11TOOL \
+                --module "$PKCS11_MODULE_PATH" \
+                --list-slots \
+                #
+            exit 0
+            ;;
+        --pkcs11-objects)
+            PKCS11_MODULE_PATH="$2"
+            PKCS11_SLOT="$3"
+            [ -n "$PKCS11_SLOT" ] ||
+                die 'Please specify library name and slot'
+            $PKCS11TOOL \
+                --module "$PKCS11_MODULE_PATH" \
+                --list-objects \
+                --login \
+                --slot "$PKCS11_SLOT" \
+                #
+            exit 0
+            ;;
 
         --help|--usage)
-		    usage
-		    exit ;;
-	--version)
-		    echo "$PROGNAME $VERSION"
-		    exit ;;
+            usage
+            exit
+            ;;
+        --version)
+            echo "$PROGNAME $VERSION"
+            exit
+            ;;
 
-	# errors
-	--*)
-		    die "$PROGNAME: unknown option: $1" ;;
-	*)
-		    break ;;
+        # errors
+        --*)
+            die "$PROGNAME: unknown option: $1"
+            ;;
+        *)
+            break
+            ;;
     esac
     shift
 done
 
 if ! [ -z "$BATCH" ]; then
-	if $OPENSSL version | grep '0\.9\.6' > /dev/null; then
-		die "Batch mode is unsupported in openssl<0.9.7"
-	fi
+    if $OPENSSL version | grep '0\.9\.6' > /dev/null; then
+        die "Batch mode is unsupported in openssl<0.9.7"
+    fi
 fi
 
 if [ $DO_ROOT -eq 1 ]; then
     if [ $DO_REQ -gt 0 -o $DO_CA -gt 0 -o $DO_P12 -gt 0 -o $DO_P11 -gt 0 ]; then
-	die "--initca and --csr and/or --sign and/or --pkcs11 and/or --pkcs12 cannot be specified together"
+        die "--initca and --csr and/or --sign and/or --pkcs11 and/or --pkcs12 cannot be specified together"
     fi
 else
     DO_REQ="${DO_REQ:-1}"
@@ -328,15 +373,15 @@ else
 fi
 
 if [ $DO_P11 -eq 1 ]; then
-	if [ $DO_P12 -eq 1 ]; then
-		die "PKCS#11 and PKCS#12 cannot be specified together"
-	fi
-	if ! grep '^pkcs11.*=' "$KEY_CONFIG" > /dev/null; then
-		die "Please edit $KEY_CONFIG and setup PKCS#11 engine"
-	fi
-	if [ -z "$PKCS11_LABEL" ]; then
-		die "PKCS#11 arguments incomplete"
-	fi
+    if [ $DO_P12 -eq 1 ]; then
+        die "PKCS#11 and PKCS#12 cannot be specified together"
+    fi
+    if ! grep '^pkcs11.*=' "$KEY_CONFIG" > /dev/null; then
+        die "Please edit $KEY_CONFIG and setup PKCS#11 engine"
+    fi
+    if [ -z "$PKCS11_LABEL" ]; then
+        die "PKCS#11 arguments incomplete"
+    fi
 fi
 
 # Set KEY_CN, FN
@@ -347,13 +392,13 @@ fi
 
 if [ -z "$KEY_CN" ]; then
     if [ -n "$1" ]; then
-	KEY_CN="$1"
+        KEY_CN="$1"
     else
-	if ! [ $DO_ROOT -eq 1 ]; then
-	    usage
-	    exit 1
-	fi
-	KEY_CN="${KEY_ORG:+$KEY_ORG }CA"
+        if ! [ $DO_ROOT -eq 1 ]; then
+            usage
+            exit 1
+        fi
+        KEY_CN="${KEY_ORG:+$KEY_ORG }CA"
     fi
 fi
 if ! [ -z "$BATCH" ]; then
@@ -415,30 +460,30 @@ if [ $DO_ROOT -eq 1 ]; then
 else
     # If we are generating pkcs12, only encrypt the final step
     if [ $DO_P12 -eq 1 ]; then
-	P12_NODES="$REQ_NODES"
-	REQ_NODES="-nodes"
+        P12_NODES="$REQ_NODES"
+        REQ_NODES="-nodes"
     fi
     # Handle subjectAltName (SAN) from KEY_SAN variable
     if [ -n "$REQ_EXT" ]; then
-	# server
-	KS1="DNS:$KEY_CN"
+        # server
+        KS1="DNS:$KEY_CN"
     else
-	if [ -n "$CA_EXT" ]; then
-	    # v3_ca (does not have ones?)
-	    KS1=""
-	    KEY_SAN=""
-	else
-	    # client
-	    KS1="email:copy"
-	fi
+        if [ -n "$CA_EXT" ]; then
+            # v3_ca (does not have ones?)
+            KS1=""
+            KEY_SAN=""
+        else
+            # client
+            KS1="email:copy"
+        fi
     fi
     if [ -n "$KEY_SAN" ]; then
-	KS2=",$KEY_SAN,"
-	if [ -n "${KS2##*,$KS1,*}" ]; then
-	    KEY_SAN="$KS1,$KEY_SAN"
-	fi
+        KS2=",$KEY_SAN,"
+        if [ -n "${KS2##*,$KS1,*}" ]; then
+            KEY_SAN="$KS1,$KEY_SAN"
+        fi
     else
-	KEY_SAN="$KS1"
+        KEY_SAN="$KS1"
     fi
     unset KS1 KS2
 fi
@@ -478,123 +523,123 @@ if [ -d "$KEY_DIR" ] && [ "$KEY_CONFIG" ]; then
 
     # Make sure $KEY_CONFIG points to the correct version of openssl.cnf
     if grep -i 'easy-rsa version 2\.[0-9]' "$KEY_CONFIG" >/dev/null; then
-	:
+        :
     else
-	echo "$PROGNAME: KEY_CONFIG (set by the ./vars script) is pointing to the wrong"
-	echo "version of openssl.cnf: $KEY_CONFIG"
-	echo "The correct version should have a comment that says: easy-rsa version 2.x"
-	exit 1
+        echo "$PROGNAME: KEY_CONFIG (set by the ./vars script) is pointing to the wrong"
+        echo "version of openssl.cnf: $KEY_CONFIG"
+        echo "The correct version should have a comment that says: easy-rsa version 2.x"
+        exit 1
     fi
 
     # Build root CA
     if [ $DO_ROOT -eq 1 ]; then
-	$OPENSSL req $BATCH -days $CA_EXPIRE -x509 \
-	    ${REQ_NODES:-${KEY_PASSPHRASE:+-passout env:KEY_PASSPHRASE}} \
-	    -new -newkey rsa:$KEY_SIZE -keyout "$FN.key" \
-	    -out "$FN.crt" \
-	    -config "$KEY_CONFIG" && \
-	chmod 0600 "$FN.key" || exit
+        $OPENSSL req $BATCH -days $CA_EXPIRE -x509 \
+            ${REQ_NODES:-${KEY_PASSPHRASE:+-passout env:KEY_PASSPHRASE}} \
+            -new -newkey rsa:$KEY_SIZE -keyout "$FN.key" \
+            -out "$FN.crt" \
+            -config "$KEY_CONFIG" && \
+        chmod 0600 "$FN.key" || exit
     else
-	# Make sure CA key/cert is available
-	if [ $DO_CA -eq 1 -o $DO_P12 -eq 1 ]; then
-	    if [ ! -s "$KEY_DIR/$CA.crt" -o ! -s "$KEY_DIR/$CA.key" ]; then
-		echo "$PROGNAME: Need a readable $CA.crt and $CA.key in $KEY_DIR"
-		echo "Try $PROGNAME --initca to build a root certificate/key."
-		exit 1
-	    fi
-	fi
+        # Make sure CA key/cert is available
+        if [ $DO_CA -eq 1 -o $DO_P12 -eq 1 ]; then
+            if [ ! -s "$KEY_DIR/$CA.crt" -o ! -s "$KEY_DIR/$CA.key" ]; then
+                echo "$PROGNAME: Need a readable $CA.crt and $CA.key in $KEY_DIR"
+                echo "Try $PROGNAME --initca to build a root certificate/key."
+                exit 1
+            fi
+        fi
 
-	# Generate key for PKCS#11 token
-	PKCS11_ARGS=
-	if [ $DO_P11 -eq 1 ]; then
-	    stty -echo
-	    echo -n "User PIN: "
-	    read -r PKCS11_PIN
-	    stty echo
-	    export PKCS11_PIN
+        # Generate key for PKCS#11 token
+        PKCS11_ARGS=
+        if [ $DO_P11 -eq 1 ]; then
+            stty -echo
+            echo -n "User PIN: "
+            read -r PKCS11_PIN
+            stty echo
+            export PKCS11_PIN
 
-	    echo "Generating key pair on PKCS#11 token..."
-	    $PKCS11TOOL --module "$PKCS11_MODULE_PATH" \
-		--keypairgen --key-type rsa:1024 \
-		--login --pin "$PKCS11_PIN"  \
-		--slot "$PKCS11_SLOT" --id "$PKCS11_ID" \
-		--label "$PKCS11_LABEL" || exit
+            echo "Generating key pair on PKCS#11 token..."
+            $PKCS11TOOL --module "$PKCS11_MODULE_PATH" \
+                --keypairgen --key-type rsa:1024 \
+                --login --pin "$PKCS11_PIN" \
+                --slot "$PKCS11_SLOT" --id "$PKCS11_ID" \
+                --label "$PKCS11_LABEL" || exit
 
-	    PKCS11_ARGS="-engine pkcs11 -keyform engine -key $PKCS11_SLOT:$PKCS11_ID"
-	fi
+            PKCS11_ARGS="-engine pkcs11 -keyform engine -key $PKCS11_SLOT:$PKCS11_ID"
+        fi
 
-	# Build cert/csr/pkey, make pkcs12 bund or load into pkcs11 token
-	if [ $DO_REQ -gt 0 ]; then
-	    if [ $DO_REQ -gt 1 -a -s "$FN.csr" ]; then
-	        DO_REQ=0
-	    else
-		$OPENSSL req $BATCH $REQ_EXT \
-		    ${REQ_NODES:-${KEY_PASSPHRASE:+-passout env:KEY_PASSPHRASE}} \
-		    -new -newkey rsa:$KEY_SIZE -keyout "$FN.key" \
-		    -out "$FN.csr" \
-		    -config "$KEY_CONFIG" \
-		    $PKCS11_ARGS && \
-		chmod -f 0600 "$FN.key" || exit
+        # Build cert/csr/pkey, make pkcs12 bund or load into pkcs11 token
+        if [ $DO_REQ -gt 0 ]; then
+            if [ $DO_REQ -gt 1 -a -s "$FN.csr" ]; then
+                DO_REQ=0
+            else
+                $OPENSSL req $BATCH $REQ_EXT \
+                    ${REQ_NODES:-${KEY_PASSPHRASE:+-passout env:KEY_PASSPHRASE}} \
+                    -new -newkey rsa:$KEY_SIZE -keyout "$FN.key" \
+                    -out "$FN.csr" \
+                    -config "$KEY_CONFIG" \
+                    $PKCS11_ARGS && \
+                chmod -f 0600 "$FN.key" || exit
 
-		DO_REQ=1
-	    fi
-	fi && \
-	if [ $DO_CA -gt 0 ]; then
-	    if [ $DO_CA -gt 1 -a -s "$FN.crt" ]; then
-		DO_CA=0
-	    else
-		days="$(ossl_cert_read_date2ts "$KEY_DIR/$CA.crt" -end)" &&
-		days="$(ossl_cert_expires_in_days "$days")" || exit
+                DO_REQ=1
+            fi
+        fi && \
+        if [ $DO_CA -gt 0 ]; then
+            if [ $DO_CA -gt 1 -a -s "$FN.crt" ]; then
+                DO_CA=0
+            else
+                days="$(ossl_cert_read_date2ts "$KEY_DIR/$CA.crt" -end)" &&
+                days="$(ossl_cert_expires_in_days "$days")" || exit
 
-		[ $days -le $KEY_EXPIRE ] || days=$KEY_EXPIRE
+                [ $days -le $KEY_EXPIRE ] || days=$KEY_EXPIRE
 
-		$OPENSSL ca $BATCH $CA_EXT -days $days -notext \
-		    ${CA_PASSPHRASE:+-passin env:CA_PASSPHRASE} \
-		    -out "$FN.crt" -in "$FN.csr" \
-		    -config "$KEY_CONFIG" && \
-		[ -s "$FN.crt" ] || exit
+                $OPENSSL ca $BATCH $CA_EXT -days $days -notext \
+                    ${CA_PASSPHRASE:+-passin env:CA_PASSPHRASE} \
+                    -out "$FN.crt" -in "$FN.csr" \
+                    -config "$KEY_CONFIG" && \
+                [ -s "$FN.crt" ] || exit
 
-		DO_CA=1
-	    fi
-	fi && \
-	if [ -n 'x' ]; then
-	    if [ $DO_P12 -gt 0 ]; then
-		$OPENSSL pkcs12 $P12_NODES -export -inkey "$FN.key" \
-		    -out "$FN.p12" -in "$FN.crt" -certfile "$CA.crt"  && \
-		chmod -f 0600 "$FN.p12" || exit
-	    else
-		! :
-	    fi || \
-	    if [ $DO_P11 -gt 0 ]; then
-		# Load certificate into PKCS#11 token
-		$OPENSSL x509 \
-		    -in "$FN.crt" -inform PEM \
-		    -out "$FN.crt.der" -outform DER && \
-		$PKCS11TOOL --module "$PKCS11_MODULE_PATH" \
-		    --write-object "$FN.crt.der" --type cert \
-		    --login --pin "$PKCS11_PIN" \
-		    --slot "$PKCS11_SLOT" --id "$PKCS11_ID" \
-		    --label "$PKCS11_LABEL" || exit
-		rm -f "$FN.crt.der"
-	    else
-		! :
-	    fi ||:
-	fi
+                DO_CA=1
+            fi
+        fi && \
+        if [ -n 'x' ]; then
+            if [ $DO_P12 -gt 0 ]; then
+                $OPENSSL pkcs12 $P12_NODES -export -inkey "$FN.key" \
+                    -out "$FN.p12" -in "$FN.crt" -certfile "$CA.crt"  && \
+                chmod -f 0600 "$FN.p12" || exit
+            else
+                ! :
+            fi || \
+            if [ $DO_P11 -gt 0 ]; then
+                # Load certificate into PKCS#11 token
+                $OPENSSL x509 \
+                    -in "$FN.crt" -inform PEM \
+                    -out "$FN.crt.der" -outform DER && \
+                $PKCS11TOOL --module "$PKCS11_MODULE_PATH" \
+                    --write-object "$FN.crt.der" --type cert \
+                    --login --pin "$PKCS11_PIN" \
+                    --slot "$PKCS11_SLOT" --id "$PKCS11_ID" \
+                    --label "$PKCS11_LABEL" || exit
+                rm -f "$FN.crt.der"
+            else
+                ! :
+            fi ||:
+        fi
     fi
 
     # Point to the key/csr/crt to help caller find ones we managed
     for f in "$FN.key" "$FN.csr" "$FN.crt"; do
-	l="last-${f##*.}"
-	[ ! -f "$f" ] || ln -sf "$f" "$l" || exit
+        l="last-${f##*.}"
+        [ ! -f "$f" ] || ln -sf "$f" "$l" || exit
     done
 
     if [ $DO_ROOT -eq 1 -o $DO_REQ -eq 1 ]; then
-	if [ -z "$BATCH" -a -n "$PASS_OPT_AUTO" ]; then
-	    # Output password to stderr only if it is terminal device
-	    fd=2 && [ -t $fd ] || PASS_OPT_AUTO='<hidden>'
-	    echo >&$fd \
-	        "Private key encrypted, password (w/o quotas): '$PASS_OPT_AUTO'"
-	fi
+        if [ -z "$BATCH" -a -n "$PASS_OPT_AUTO" ]; then
+            # Output password to stderr only if it is terminal device
+            fd=2 && [ -t $fd ] || PASS_OPT_AUTO='<hidden>'
+            echo >&$fd \
+                "Private key encrypted, password (w/o quotas): '$PASS_OPT_AUTO'"
+        fi
     fi
 
     # Report actions we performed to /dev/fd/3. This can be used for example
@@ -602,14 +647,14 @@ if [ -d "$KEY_DIR" ] && [ "$KEY_CONFIG" ]; then
     # existing csr is used to create (renew) certificate with behaviour
     # activated using --sign parameter.
     {
-	echo >&3 "
-	    FN='$FN'
-	    DO_ROOT='$DO_ROOT'
-	    DO_REQ='$DO_REQ'
-	    DO_CA='$DO_CA'
-	    DO_P12='$DO_P12'
-	    DO_P11='$DO_P11'
-	"
+        echo >&3 "
+            FN='$FN'
+            DO_ROOT='$DO_ROOT'
+            DO_REQ='$DO_REQ'
+            DO_CA='$DO_CA'
+            DO_P12='$DO_P12'
+            DO_P11='$DO_P11'
+        "
     } >/dev/null 2>&1 ||:
 else
     # Need definitions
